version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    ports:
      - "9080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command:
      - start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data
  
  reactivitybackend:
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    container_name: reactivitybackend
    ports:
      - "9081:8080"
    depends_on:
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__sql1=Server=sql2,1433;Database=commanddb;User Id=sa;Password=@Bcd.1234;TrustServerCertificate=True

volumes:
  keycloak-data: